# Generated by Django 3.2.2 on 2022-04-04 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_posts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 13, 50, 38, 405219, tzinfo=utc)),
        ),
    ]
